version: "3.8"

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  kibanadata:
    driver: local

networks:
  default:
    name: elastic
    external: true

services:
  kibana:
    container_name: kibana
    depends_on:
      es01:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.12.2
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
    mem_limit: 4294967296
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - xpack.ml.max_machine_memory_percent=50
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false 
      - xpack.security.http.ssl.enabled=false 
      - xpack.security.transport.ssl.enabled=false
      - discovery.type=single-node
      - xpack.license.self_generated.type=basic
    mem_limit: 4294967296
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    user: elasticsearch
    command: >
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q analysis-icu || 
      ./bin/elasticsearch-plugin install analysis-icu; 
      ./bin/elasticsearch-plugin list | grep -q analysis-kuromoji || 
      ./bin/elasticsearch-plugin install analysis-kuromoji; 
      /usr/local/bin/docker-entrypoint.sh"
  
